// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf9IMEqlfUFPPTyu_s_KoOmEXyMPzZ6XQ',
    appId: '1:822544101343:web:33cbb8f3b3eecf23611e6a',
    messagingSenderId: '822544101343',
    projectId: 'bloodlink-ai-33f90',
    authDomain: 'bloodlink-ai-33f90.firebaseapp.com',
    storageBucket: 'bloodlink-ai-33f90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPAN2IWQ9u51zS5zk0GhEMe1jxvcrYCnU',
    appId: '1:822544101343:ios:f12af4c097a67438611e6a',
    messagingSenderId: '822544101343',
    projectId: 'bloodlink-ai-33f90',
    storageBucket: 'bloodlink-ai-33f90.firebasestorage.app',
    iosBundleId: 'com.example.bloodlinkAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPAN2IWQ9u51zS5zk0GhEMe1jxvcrYCnU',
    appId: '1:822544101343:ios:f12af4c097a67438611e6a',
    messagingSenderId: '822544101343',
    projectId: 'bloodlink-ai-33f90',
    storageBucket: 'bloodlink-ai-33f90.firebasestorage.app',
    iosBundleId: 'com.example.bloodlinkAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf9IMEqlfUFPPTyu_s_KoOmEXyMPzZ6XQ',
    appId: '1:822544101343:web:33cbb8f3b3eecf23611e6a',
    messagingSenderId: '822544101343',
    projectId: 'bloodlink-ai-33f90',
    authDomain: 'bloodlink-ai-33f90.firebaseapp.com',
    storageBucket: 'bloodlink-ai-33f90.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsnRM95YovPJlqCTOZLIuTsOrN1kKQkX0',
    appId: '1:822544101343:android:03e1f121ec5319f8611e6a',
    messagingSenderId: '822544101343',
    projectId: 'bloodlink-ai-33f90',
    storageBucket: 'bloodlink-ai-33f90.firebasestorage.app',
  );

}